'1 - Realize qualquer operação matemática envolvendo dois números

10 LET X = 10 
20 LET Y = 20 
30 LET RES = X+Y
40 PRINT RES

'2 - Leia e então imprima um número

10 INPUT "Entre com um número: "; NUM
20 PRINT NUM

'3 - Leia 2 números e realize qualquer operação matemática envolvendo eles

10 INPUT "Entre com o primeiro número: "; NUM1
20 INPUT "Entre com o segundo número: "; NUM2
30 LET RES = NUM1 - NUM2 *-1 (SOMA VAI SOMAR STRING)
40 PRINT RES

